### ISSUE TITLE
Social share button is not showing up in chrome and safari

### ISSUE THREAD

**Issue by rameshcharykotha** [brianpkelley/video-js-4-plugins#10]
I am able to view the share button in mozilla, where as in rest of other browsers nothing is shown up in the place of share button. Could you please tell me do i need to include any extra files, to make it work in chrome and rest of the browsers. Thanks for the help.

Below files i have included in the page.
```javascript
<!-- VideJS files -->
<link href="css/video-js.min.css" rel="stylesheet">
<script src="js/video.dev.js"></script>

<!-- Plugins -->
<link href="css/videojs.addThis.css" rel="stylesheet">
<script src="js/videojs.addThis.js"></script>

below is the set up am using. 
<script type="text/javascript">
videojs("videoId", {
	width : 550,
	height : 315,
    plugins: {
        addThis: {
          reddit: false,
          delicious: false,
          //website_url: "http://www.google.com",
          embed : true,
          more : false
        }
    }
}, function(){
// Player (this) is initialized and ready.
});
</script>
```
moziall image:
![mozilla](https://cloud.githubusercontent.com/assets/331757/9121101/d958b6d8-3c9d-11e5-8169-d05516990ac0.jpg)
chrome image:
![chrome](https://cloud.githubusercontent.com/assets/331757/9121107/e2177066-3c9d-11e5-9cee-20ad23161ba0.jpg)

**Comment by brianpkelley** [comment]
Do you have a demo uploaded anywhere I could take a look at it?

**Comment by rameshcharykotha** [comment]
It is working fine after replacing below lines, i was using older version. 
````javascript
<link href="//cdnjs.cloudflare.com/ajax/libs/video.js/4.9.1/video-js.css" rel="stylesheet">
<script src="//cdnjs.cloudflare.com/ajax/libs/video.js/4.9.1/video.dev.js" type="text/javascript"></script>
````
Thanks.
