### ISSUE TITLE
Video.js 5.x?

### ISSUE THREAD

**Issue by alijaffar** [brianpkelley/video-js-4-plugins#12]
It seems you've made some awesome plugins, though they've since deprecated :(

**Comment by koenokatachi** [comment]
I support this issue. @brianpkelley do you plan update addThis plugin to videojs5?

**Comment by brianpkelley** [comment]
As of right now, there are no plans to migrate to vjs 5.x Sorry.  The project these were created for is in a stable and deployed state, coupled with all the other projects that are on going it will be some time before any more attention is diverted to the video player.
