### ISSUE TITLE
addThis plugin does not work with last version of videojs

### ISSUE THREAD

**Issue by RomanEmelyanov** [brianpkelley/video-js-4-plugins#5]
After replace
```javascript
<link href="video-js.min.css" rel="stylesheet" />
<script src="video.dev.js"></script>
```
to
```javascript
<link href="//vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.11/video.js"></script>
```
in example
https://github.com/brianpkelley/video-js-4-plugins/blob/master/addThis/index.html

Google Chrome browser give me a error:

Uncaught TypeError: Cannot read property 'id' of undefined

**Comment by Zatara7** [comment]
I think the problem is that you're not including the dev build --> video.dev.js

**Comment by brianpkelley** [comment]
@RomanEmelyanov @Zatara7 is correct.  You need to include the dev version of videojs as it is unminified and the variables have not be renamed.
