### ISSUE TITLE
playlist plugin

### ISSUE THREAD

**Issue by da1nonly** [brianpkelley/video-js-4-plugins#6]
hi i was wondering to to use the videojs playlist plugin.

**Comment by brianpkelley** [comment]
There is an example of the plugin object here:
https://github.com/brianpkelley/video-js-4-plugins/blob/master/playlist/playlist.js#L352-L385

I seriously do not know why I'm not getting notifications on my own repo, yet I get 500 emails on other repo's I'm watching...
