### ISSUE TITLE
the plugin does not work with videojs 4.9+

### ISSUE THREAD

**Issue by koenokatachi** [brianpkelley/video-js-4-plugins#8]
videojs css for versions below 4.9 has

```
.vjs-default-skin .vjs-menu-button:hover .vjs-menu{
	display:block
}
```

for 4.9+ it is
```
.vjs-default-skin .vjs-menu-button:hover .vjs-control-content .vjs-menu,.vjs-default-skin .vjs-control-content .vjs-menu.vjs-lock-showing{
	display:block
}
```

so 4.9+ supposes ```.vjs-menu``` inside of ```.vjs-control-content``` but ur plugin puts them along as sibling nodes.

because of this the sharing menu doesnt open on hovering the plugin button

**Comment by brianpkelley** [comment]
Thank you for the heads up.  I've been rather busy with a newborn and work, I'll try to address asap.

Do you have an example I could look at?

I'll keep this issue open for other people as well.

**Comment by koenokatachi** [comment]
cheers to ur baby ^^ and thanks for ur time

here is a demo http://37.1.195.56/share/vjs/

as is it loads vjs 4.9.1.

u can change the vjs version is loads via the "v" url parameter.
for example http://37.1.195.56/share/vjs/?v=4.8.5 load vjs 4.8.5

what i mean sayin "it doesnt work". open a link and hover the addthis plugin button. in vjs 4.9+ the menu doesnt show itself on the button hover.

so it works in
http://37.1.195.56/share/vjs/?v=4.5.2
http://37.1.195.56/share/vjs/?v=4.6.4
http://37.1.195.56/share/vjs/?v=4.7.3
http://37.1.195.56/share/vjs/?v=4.8.5

but it doesnt work in
http://37.1.195.56/share/vjs/?v=4.9.1
http://37.1.195.56/share/vjs/?v=4.10.2
http://37.1.195.56/share/vjs/?v=4.11.4
http://37.1.195.56/share/vjs/?v=4.12.5

check out my first comment for some details

**Comment by brianpkelley** [comment]
Can you pull down the latest file and test again.  I removed the custom createEl function from the menu button which seems to have fixed the issue.

**Comment by koenokatachi** [comment]
ive updated my demo. yes, it looks like fixed. thanks

**Comment by brianpkelley** [comment]
Thanks for reporting and the help getting this resolved!
